### ISSUE TITLE
Support `--no-docs-gen` argument

### ISSUE THREAD

**Issue by arendjr** [autometrics-dev/autometrics-go#38]
The purpose of this argument is to disable documentation generation by the generator. This would allow the VS Code extension to become solely responsible for generating documentation tooltips.

This is a blocker for finalizing https://github.com/autometrics-dev/vscode-autometrics/issues/28

Feel free to suggest a better name for the argument :sweat_smile:

**Comment by gagbo** [comment]
It probably needs to be an environment argument, because it's not possible to call `go generate ./...` with a flag that will get passed to the `autometrics` binary.

When this change is being made, it's also going to be the opportunity to finalize the "directive comment" API, probably as

```patch
-//autometrics:doc --slo "API" --latency-target 99 --latency-ms 250
+//autometrics:inst [--no-doc] --slo "API" --latency-target 99 --latency-ms 250
```

But undecided yet
